fix naddr field of CDPMsgAddr
secdev/scapy pull request #2829
Opened 2020-09-23 04:28 UTC by cq674350529

The `naddr` filed is the count of how many `CDPAddrRecord` contained in the `addr` field, not its total length. So use `count_of` instead.

2020-09-23 07:24 UTC, guedou requested changes
Could you add a unit test for this change? Thanks.

2020-09-23 13:34 UTC, cq674350529 commented
A simple test for `naddr` field of `CDPMsgAddr` was added. I'm not sure if it's proper.  I intend to build the cdp packet from raw bytes, but it seems that the `FieldLenField` won't be updated when calling  `raw()` or `build()` later. So build the packet using `CDPMsgAddr` directly.

By the way, sorry for the typos in commits, for I didn't find a way to run `cdp.uts` in my local env easily.

2020-09-23 17:36 UTC, guedou commented
No problem. I will squash the commits.  You could launch them with `./test/run_tests -P "load_contrib('cdp')" -t test/contrib/cdp.uts`

2020-09-23 17:36 UTC, merged

2020-09-24 01:37 UTC, cq674350529 commented
Got it, thanks!