volatile: add command method to be used in Packet.command()
secdev/scapy pull request #2839
Opened 2020-09-30 08:47 UTC by ThomasFaivre

When a VolatileValue subclass is used inside a Packet, the command()
method returns a string that get a Syntax Error when evaluated, e.g.:

> ICMPv6NIQueryNOOP(nonce=<RandBin>)

Add a command() method to the VolatileValue class so that it can be
handled properly. The _command_args() method is used to defined the
string used as argument for a given VolatileValue subclass.

Default values are not displayed.

Fixes #2828.

Signed-off-by: Thomas Faivre <thomas.faivre@6wind.com>

2020-09-30 09:41 UTC, ThomasFaivre commented
Not sure what I can do about Codacy. The purpose of this method is to get overridden by sub-classes.
Any advice?

Also, coverage went down a little, that's because I only added command test for classes that were already being tested.

2020-10-01 08:44 UTC, guedou requested changes
Thanks for the long PR!

2020-10-01 08:44 UTC, guedou commented on scapy/volatile.py
> +        # XXX: only outputs the list of keys, but values are irrelevant anyway
Could you replace `XXX` with `Note` ?

2020-10-01 08:44 UTC, guedou commented on scapy/volatile.py
> +        if self.ip.repr == "0.0.0.0/0":
Could use a `_DEFAULT_IPTEMPLATE `variable as you did with `_DEFAULT_CHARS`?

2020-10-01 18:48 UTC, merged