Improve http_request
secdev/scapy pull request #2843
Opened 2020-09-30 22:20 UTC by gpotter2

- small improvement in `http_request` to use a native socket when possible. This has the advantage to work without sudo
- change test domain from kame to secdev, because the former was unstable at times

2020-10-12 06:50 UTC, guedou requested changes

2020-10-12 06:50 UTC, guedou commented on scapy/layers/http.py
> +                     On linux, you'll almost certainly need this.
s/linux/Linux.

2020-10-12 06:50 UTC, guedou commented on scapy/layers/http.py
> +            assert(os.system(iptables_rule % ('D', host)) == 0)
We should call `host = str(Net(host))` again before `os.system()` to make sure that `host` in the not a shell command that can be injected into iptables_rule.

2020-10-14 18:50 UTC, gpotter2 commented
@guedou I fixed both of your comments. Thanks

2020-10-15 09:03 UTC, merged