Supporting zstd for HTTP compression
secdev/scapy pull request #2852
Opened 2020-10-07 01:01 UTC by starrify

Notice that it may occur in the Content-Encoding field but not (yet) in Transfer-Encoding, according to the IANA registry: https://www.iana.org/assignments/http-parameters/http-parameters.xhtml

Creating this draft PR for now for review and comments, despite the fact that it has NOT yet passed the tests.

The test failure seems to be a rather weird one, as it parses no packet at all from the added pcap file at this line: `pkts = sniff(offline=filename, session=TCPSession)`. Example from a local execution of the UTscapy tool:
```
$ python -m scapy.tools.UTscapy -c ./test/configs/linux.utsc

>>> print(pkts)
<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>
>>> pkts[0].show()
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "***/scapy/scapy/plist.py", line 133, in __getitem__
    return self.res.__getitem__(item)
IndexError: list index out of range
```

While the expected result is to at least parse the TCP and HTTP packets. Example from a local installation of this branch (`pip install .`):
```
$ scapy
>>> load_layer('http')
>>> sniff(offline='./test/pcaps/http_compressed-zstd.pcap')
<Sniffed: TCP:1 UDP:0 ICMP:0 Other:0>
>>> _.show()
0000 Ether / IP / TCP / HTTP / 'HTTP/1.1' '200' 'OK' / Raw
```

I'm afraid that the observations above might suggest some further issue, possibly related to the tests.

2020-10-07 19:29 UTC, gpotter2 requested changes
Cool PR thanks ! This should be easy enough.

2020-10-07 19:29 UTC, gpotter2 commented on test/regression.uts
> +pkts = sniff(offline=filename, session=TCPSession)
If you're using `TCPSession`, the packets are only returned when complete. Your pcap only contains a single TCP fragment and not the whole HTTP frame, so you likely just want to remove the use of `TCPSession`.

2020-10-07 21:26 UTC, starrify commented
Hi @gpotter2 , thanks a lot for the kind check! (and apologies for my silliness in having missed that :sweat_smile:)
The changes have been now updated to fix the issues in the test.

2020-10-11 11:28 UTC, gpotter2 approved these changes

2020-10-11 11:28 UTC, merged