Adds support for Unique Local Addresses
secdev/scapy pull request #2856
Opened 2020-10-07 22:17 UTC by n-thumann

As suggested in https://github.com/secdev/scapy/issues/399, this PR adds support for detecting Unique Local Addresses.

2020-10-09 09:31 UTC, gpotter2 submitted a review, later dismissed
I'll let @guedou review it but it looks fine to me ! Thanks for the PR

2020-10-23 08:21 UTC, guedou requested changes
Thanks for this really difficult PR! I think that only in6_getAddrType() should be changed.

2020-10-23 08:21 UTC, guedou commented on scapy/utils6.py
> +    if in6_isgladdr(addr):
According to https://tools.ietf.org/html/rfc4193#section-3.3 the scope is global. This function should not be modified.

2020-10-23 08:21 UTC, guedou commented on scapy/utils6.py
> +        if in6_isaddr6to4(addr):  # Mark 6to4
Please replace @ with address instead of removing it.

2020-10-23 08:21 UTC, guedou commented on scapy/utils6.py
> -# TODO : integrate Unique Local Addresses
Do not remove the other comments.

2020-10-23 08:21 UTC, guedou commented on scapy/utils6.py
> +        addrType = (IPV6_ADDR_UNICAST | IPV6_ADDR_UNIQUE_LOCAL)
It should also be IPV6_ADDR_GLOBAL

2020-10-23 08:21 UTC, guedou commented on scapy/utils6.py
> -    if in6_isgladdr(addr) or in6_isuladdr(addr):
I am not convinced that this change is correct. Did you test it on Linux with unique local addresses? It seems that the Linux kernel does not specify IPV6_ADDR_UNIQUE_LOCAL. Therefore, this patch will likely break address selection.

2021-09-12 07:00 UTC, guedou commented
I am closing this PR as we did not receive an answer, and that I doubt that it works correctly.

2021-09-12 07:00 UTC, closed without merging