Use lazy formatting in logging calls
secdev/scapy pull request #2889
Opened 2020-10-19 14:38 UTC by akorb

See https://stackoverflow.com/q/34619790/2050020

2020-10-20 16:07 UTC, gpotter2 approved these changes
Thanks for the PR. Sounds reasonable (though we're definetly not after this kind of performance 😄)

2020-10-20 16:07 UTC, gpotter2 commented on scapy/packet.py
> +                        log_runtime.error("%s.guess_payload_class() returned [%s]", self.__class__.__name__, repr(cls))  # noqa: E501
Would be cool if you could get rid of the noqa while you're at it. Thanks

2020-10-20 16:07 UTC, gpotter2 commented on scapy/pipetool.py
> +                            log_runtime.exception("piping from %s failed: %s", fd.name, e)  # noqa: E501
same

2020-10-21 07:24 UTC, guedou requested changes
Thanks for the PR! I have the comments as @gpotter2 regarding the noqa tags.

2020-10-21 14:28 UTC, akorb commented
I applied the comments and changed some more code in the same fashion with `warning`

2020-10-22 00:14 UTC, p-l- approved these changes

2020-10-22 00:14 UTC, p-l- commented
@guedou is it OK for you now?

2020-10-22 07:56 UTC, merged