Standalone NTP unit tests
secdev/scapy pull request #2915
Opened 2020-10-26 08:00 UTC by polybassa

Co-authored-by: Pierre Lalet <pierre@droids-corp.org>, <pierre.lalet@cea.fr>
Co-authored-by: Pierre Lorinquer <pierre.lorinquer@ssi.gouv.fr>
Co-authored-by: Neurocinetics <0901653@student.hr.nl>
Co-authored-by: Gabriel Potter <gabriel@potter.fr>
Co-authored-by: Guillaume Valadon <guillaume.valadon@netatmo.com>

2020-10-26 08:14 UTC, guedou commented
@polybassa please sync with me and wait for my Ok before pushing more of these PR. We are already working on similar files =/

2020-10-26 08:16 UTC, polybassa commented
@guedou Alright. Sorry. I will wait for your OK.

2020-10-26 08:17 UTC, guedou commented
No problem. We will likely run into conflicts nightmares if we rush in pushing this PR too fast =)

2020-10-26 08:19 UTC, polybassa commented
Probably. I tried to find pretty much isolated sections in regression.uts. Therefore I have chosen random and ntp.

2020-10-26 17:44 UTC, guedou commented
`regression.uts` contains other parted related to NTP =/

2020-10-26 17:46 UTC, polybassa commented
Oh... should I update right now? Or should I better wait until you finished your PR?

2020-10-26 18:07 UTC, polybassa commented
I've updated.

2020-10-26 18:33 UTC, guedou requested changes
I made some comments about that should stay in regression.uts. The other changes are good to me.

2020-10-26 18:33 UTC, guedou commented on test/regression.uts
> -= fuzz on packets with advanced RandNum
IMHO, this should stay in `regression.uts` as it is not a NTP specific test.

2020-10-26 18:33 UTC, guedou commented on test/regression.uts
> -~ basic IP TCP UDP NTP LLC SNAP Dot11
IMHO, this should stay in `regression.uts` as it is not a NTP specific test.

2020-10-26 18:33 UTC, guedou commented on test/regression.uts
> -Ether()/IP()/UDP()/NTP()
IMHO, this should stay in `regression.uts` as it is not a NTP specific test.

2020-10-26 18:33 UTC, guedou commented on test/regression.uts
> -= sprintf() function
IMHO, this should stay in `regression.uts` as it is not a NTP specific test.

2020-10-27 07:31 UTC, polybassa commented
Hi, I changed everything back, except the `specific haslayer and getlayer implementations for NTP` test

2020-10-28 13:34 UTC, guedou commented
Looks good to me! Could you split VXLAN?

2020-10-28 13:36 UTC, polybassa commented
Yes. VXLAN is here: #2913

2020-10-28 18:46 UTC, guedou commented
Sorry I meant VRRP.

2020-10-31 08:35 UTC, guedou commented
LGTM. Could you rebase againt master?

2020-10-31 08:36 UTC, guedou commented
Could you do TFTP next?

2020-10-31 08:45 UTC, polybassa commented
Yes, I will do tftp next. I will rebase later, today. 
-- 
Viele Grüße

Nils Weiß

On October 31, 2020 9:36:42 AM GMT+01:00, Guillaume Valadon <notifications@github.com> wrote:
>Could you do TFTP next?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/secdev/scapy/pull/2915#issuecomment-719903819

2020-10-31 13:38 UTC, polybassa commented
Done

2020-10-31 14:13 UTC, merged