Improve GroupManagementCipherSuite detection
secdev/scapy pull request #3152
Opened 2021-03-27 22:48 UTC by gpotter2

fixes https://github.com/secdev/scapy/issues/3115

2021-04-12 13:28 UTC, guedou requested changes
Could you add a unit test?

2021-04-13 08:29 UTC, p-l- approved these changes

2021-04-13 12:19 UTC, gpotter2 commented
I've added a test

2021-04-14 14:35 UTC, p-l- approved these changes

2021-04-14 18:51 UTC, merged