TCP defragmentation fixed
secdev/scapy pull request #3279
Opened 2021-07-01 16:25 UTC by xiaohuihui1024

Fixed display issues with TCP defragmentation on Wireshark

fixes #3277

2021-07-01 23:11 UTC, gpotter2 requested changes
Thanks for the report & the request !
It looks rather good, but I have a few comments.

Could you also inclde a simple unit test? Thanks !

2021-07-01 23:11 UTC, gpotter2 commented on scapy/sessions.py
> +            metadata["seq"] = pkt[TCP].seq
We already have a `seq = pkt[TCP].seq` so you can just re-use it.

2021-07-01 23:11 UTC, gpotter2 commented on scapy/sessions.py
> +            if metadata["seq"] is not None:
Shouldn't it be `"seq" in metadata` ?

2021-07-01 23:11 UTC, gpotter2 commented on scapy/sessions.py
> +            pkt.wirelen = len(raw(pkt))
This is technically incorrect since this is not the wirelen, but you can do
```
pkt.wirelen = None
```
to have the same effect

2021-07-02 02:34 UTC, xiaohuihui1024 commented
I updated the code and committed it, but I don't know how to unit test.

I tested it with the following code:

```python
from scapy.all import *
from scapy.utils import *
load_layer("tls")
conf.tls_session_enable = True
print(conf.version)


class TLS_over_TCP(TLSSession, TCPSession):
    pass


pkts = sniff(offline=r"192.168.165.217_49183_156.38.206.18_443_1593515552.pcap",
             session=TLS_over_TCP)

wrpcap("xxx.pcap", pkts)

```
You can get the `pcap` file from

[192.168.165.217_49183_156.38.206.18_443_1593515552.pcap](https://drive.google.com/file/d/1iyIHMY5tWIuNQjggQMawIliQndh9ojB8/view?usp=sharing)

The results after running the code are shown below.

![image](https://user-images.githubusercontent.com/20126304/124212168-12c16500-db21-11eb-8599-4d65fcd209f9.png)

2021-07-13 23:29 UTC, gpotter2 commented
Thanks for the detailed explanation, I've added a unit test for you.

2021-07-19 22:53 UTC, merged