Split 3054 minor changes
secdev/scapy pull request #3309
Opened 2021-07-28 08:39 UTC by polybassa

Minor fixes to the current code. Could this PR please get merged previously to #3283 and #3054

2021-07-28 09:46 UTC, polybassa commented
@gpotter2 Can this PR get merged, please?

2021-07-31 23:21 UTC, gpotter2 requested changes

2021-07-31 23:21 UTC, gpotter2 commented on test/contrib/automotive/interface_mockup.py
> +    if not ISOTPSocket == ISOTPNativeSocket:  # type: ignore
You should be using the `is` operator

2021-07-31 23:21 UTC, gpotter2 commented on test/contrib/automotive/interface_mockup.py
> +        return pkt
This function is a duplicate. Import it

2021-07-31 23:21 UTC, gpotter2 commented on test/contrib/automotive/interface_mockup.py
> +            return None
same?

2021-07-31 23:21 UTC, gpotter2 commented on test/contrib/automotive/gmlan_trace.candump
> -(0.297000) vcan2 12A#122010FF00001080
It's a bummer this even got into here in the first place.. I'll try to be much more careful reviewing stuff from now on

2021-08-02 07:04 UTC, polybassa commented on test/contrib/automotive/interface_mockup.py
> +    if not ISOTPSocket == ISOTPNativeSocket:  # type: ignore
Done

2021-08-02 07:04 UTC, polybassa commented on test/contrib/automotive/interface_mockup.py
> +        return pkt
Done

2021-08-02 07:04 UTC, polybassa commented on test/contrib/automotive/interface_mockup.py
> +            return None
Done

2021-08-02 07:07 UTC, polybassa commented
Feedback applied

2021-08-18 06:33 UTC, polybassa commented
@gpotter2 can this PR get merged, please?

2021-08-18 08:02 UTC, gpotter2 approved these changes

2021-08-18 08:03 UTC, merged