Fix typo in "answser".
secdev/scapy pull request #3451
Opened 2021-11-22 01:33 UTC by Jetsie

In the docs @ [https://scapy.readthedocs.io/en/latest/layers/http.html](this page), there is a typo in the word answer, spelt incorrectly as "answser".

2021-11-22 07:43 UTC, guedou requested changes

2021-11-22 07:43 UTC, guedou commented on doc/scapy/layers/http.rst
> +The HTTP 2 documentation is available as a Jupyther notebook over here: `HTTP 2 Tuto <https://github.com/secdev/scapy/blob/master/doc/notebooks/HTTP_2_Tuto.ipynb>`_
It seems that this change is not needed. However, it noticed that the right spelling is Jupyter.

2021-12-19 19:50 UTC, polybassa approved these changes

2022-03-28 08:10 UTC, closed without merging

2022-03-28 08:11 UTC, polybassa commented
Closed since #3542 got merged