Pcapreader() does not work with PosixPath and WindowsPath fix #3596
secdev/scapy pull request #3597
Opened 2022-05-04 15:38 UTC by tanwirahmad

`Pcapreader()` works fine even if the provided `filename` is in PosixPath or WindowsPath type. Fix #3596

I don't know if this PR requires unit tests. If it does, then please guide me where they can be added.

2022-05-05 18:11 UTC, p-l- requested changes
Thanks for this fix. I think we can (should?) use `os.PathLike` here. What do you think?

2022-05-05 18:11 UTC, p-l- commented on scapy/utils.py
> +import pathlib
```suggestion
```

2022-05-05 18:11 UTC, p-l- commented on scapy/utils.py
> +    def open(fname  # type: Union[IO[bytes], str, pathlib.PosixPath, pathlib.WindowsPath]
```suggestion
    def open(fname  # type: Union[IO[bytes], str, bytes, os.PathLike]
```
See https://peps.python.org/pep-0519/#provide-specific-type-hinting-support

2022-05-05 18:11 UTC, p-l- commented on scapy/utils.py
> +        if isinstance(fname, (str, pathlib.PosixPath, pathlib.WindowsPath)):
```suggestion
        if isinstance(fname, (str, bytes, os.PathLike)):
```

2022-05-05 18:57 UTC, tanwirahmad commented
I didn't know about `os.PathLike`. It makes perfect sense!

2022-05-05 19:28 UTC, p-l- approved these changes

2022-05-06 07:14 UTC, p-l- commented
Anyway, not sure it was a good idea after all, since Python 2.7 lacks  `os.PathLike`... Sorry about that :-/

2022-05-06 13:12 UTC, p-l- commented
Sorry, I think it is better to come back to your first option, it was better since it would have worked with Python 2 directly, am I wrong?

2022-05-09 07:30 UTC, gpotter2 commented
Unsure this PR is really necessary: there are quite a few ways to get the full absolute path from the `Path...` object :/

2022-05-09 12:21 UTC, tanwirahmad commented
@gpotter2 The purpose of this PR is to support `os.PathLike` objects for `Pcapreader()`. IMHO, they are more useful than strings based paths. 

@p-l- My first option would not have worked for Python 2 because the `pathlib` library was added in Python 3.4

2022-05-09 12:45 UTC, p-l- commented on scapy/utils.py
> +            allowed_fname_types = (str, bytes)  # type: ignore
```suggestion
            allowed_fname_types = (str, bytes)  # type: ignore
```
The trailing space will cause tests failure.

2022-05-16 21:19 UTC, gpotter2 commented on scapy/utils.py
> +            allowed_fname_types = (str, bytes)  # type: ignore
I would rather move this outside the runtime (e.g.: in `six.compat`, but you'll have to rename it something more meaningful)

2022-07-26 20:41 UTC, gpotter2 requested changes
- **PR doesn't pass both PEP8 and Mypy tests**
- I said `scapy.compat`, not scapy.libs.six because we regularly update it so any changes in there would be lost.
- PR is wrong because:
  - `filename = fname` is wrong in case of an `os.PathLike`... it's not the filename anymore
  - you can't just change the return type of `filename` to `Union[...]` just to make it pass the tests, you need to actually fix it

2022-07-26 20:47 UTC, gpotter2 commented
(As for the doc build failure: https://github.com/sphinx-doc/sphinx/issues/10710)

2022-07-27 05:04 UTC, guedou commented
I am unsure this PR is necessary.

2022-07-27 07:31 UTC, gpotter2 commented
I kinda agree. Are we really going to update every function in Scapy to support path stuff, when in one call you can get the absolute path

2022-10-08 10:19 UTC, closed without merging

2022-10-08 10:19 UTC, guedou commented
I am closing this PR as Scapy maintainers seem that it is not necessary.