Add packet as underlayer to all packets in PacketListField
secdev/scapy pull request #3607
Opened 2022-05-13 09:27 UTC by matsievskiysv

**Checklist:**

-   [x] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [x] I squashed commits belonging together
-   [x] I added unit tests or explained why they are not relevant
-   [x] I executed the regression tests for Python2 and Python3 (using `tox` or, `cd test && ./run_tests_py2, cd test && ./run_tests_py3`)
-   [x] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

This trivial PR adds the current packet as an underlayer to all packets in PacketListField, providing a way to reference lower protocol layers from the packet object. This is particularly useful for implementation of guess_payload_class method for the elements of PacketListField.

2022-05-13 10:44 UTC, matsievskiysv commented
In particular, this feature was used to determine GVRP/GMRP payload of the GARP protocol based on destination MAC [here](https://github.com/matsievskiysv/scapy/blob/master/scapy/contrib/gxrp.py#L124-L139)

2022-05-17 09:33 UTC, p-l- commented
While I understand the rationale, I don't think this is a correct solution: `.underlayer` has a meaning, and this PR uses it in a wrong way. I think it would be better to have a different, non-ambiguous attribute, and use it instead.

What do you think?

2022-05-17 09:34 UTC, p-l- requested changes
While I understand the rationale, I don't think this is a correct solution: `.underlayer` has a meaning, and this PR uses it in a wrong way. I think it would be better to have a different, non-ambiguous attribute, and use it instead.

What do you think?

2022-05-17 09:50 UTC, matsievskiysv commented
> I think it would be better to have a different, non-ambiguous attribute, and use it instead.

What should it be called? Something like a `parent`?

2022-05-17 11:42 UTC, p-l- commented
I like `parent`! An opinion @gpotter2 @guedou and others?

2022-05-17 15:19 UTC, matsievskiysv commented
@p-l- if this version is ok, I'll proceed with adding the tests.

2022-05-17 15:31 UTC, gpotter2 commented
I will have to check but I'm almost sure the behavior with `underlayer` is already used by **some** fields, somewhere. We should either find those, or, for consistency's stake, keep `underlayer`

2022-05-17 16:48 UTC, matsievskiysv commented
BTW, maybe `listparent` would be more appropriate?

2022-05-17 20:53 UTC, guedou commented
Parent sounds good we

2022-05-18 04:56 UTC, matsievskiysv commented
@p-l- I think it's ready for the review

2022-05-18 09:58 UTC, p-l- requested changes
Apart from that, LGTM

2022-05-18 09:58 UTC, p-l- commented on scapy/fields.py
> +            if issubclass(type(p), BasePacket):
```suggestion
            if isinstance(p, BasePacket):
```

2022-05-18 09:59 UTC, p-l- commented on scapy/fields.py
> +    referenced in parent field.
```suggestion
    (i.e. a stack of layers). All elements in PacketListField have current
    packet referenced in parent field.
```
That should fix the flake8 failure

2022-05-18 15:21 UTC, p-l- approved these changes

2022-05-18 17:34 UTC, merged

2022-05-18 18:23 UTC, matsievskiysv commented
Shit. The final  version does not work with `guess_payload_class` anymore. `parent` should be added to class at construction time, otherwise it's too late. This should teach me to write proper tests for this kind of stuff. I'll fix it in separate PR.