Stabilize UDS_Scanner unit tests for appveyor
secdev/scapy pull request #3615
Opened 2022-05-20 06:51 UTC by polybassa

The UDS-Scanner unit tests sometimes fail because of an internal error in the underlying `ObjectPipe`. 
Apparently, Windows is silently closing the notification file used in `ObjectPipe` during the unit test. 

This PR is a patch to recreate a new `TestSocket` aka. `ObjectPipe` once this error appears. 

This PR should stabilize the UDS and GMLAN Scanner unit tests. 

```
[i] Start execution of enumerator: Wed May 18 17:47:48 2022
Exception in thread Thread-2777:
Traceback (most recent call last):
  File "C:\Python37-x64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python37-x64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\projects\scapy\scapy\ansmachine.py", line 202, in __call__
    self.sniff()
  File "C:\projects\scapy\scapy\ansmachine.py", line 208, in sniff
    sniff(**self.optsniff)
  File "C:\projects\scapy\scapy\sendrecv.py", line 1310, in sniff
    sniffer._run(*args, **kwargs)
  File "C:\projects\scapy\scapy\sendrecv.py", line 1257, in _run
    session.on_packet_received(p)
  File "C:\projects\scapy\scapy\sessions.py", line 106, in on_packet_received
    result = self.prn(pkt)
  File "C:\projects\scapy\scapy\ansmachine.py", line 181, in reply
    self.send_reply(reply)
  File "C:\projects\scapy\scapy\contrib\automotive\ecu.py", line 712, in send_reply
    self._main_socket.send(p)
  File "C:\projects\scapy\test\testsocket.py", line 69, in send
    super(TestSocket, r).send(sx)  # type: ignore
  File "C:\projects\scapy\scapy\automaton.py", line 183, in send
    os.write(self.__wr, b"X")
OSError: [Errno 9] Bad file descriptor
```

2022-05-21 18:08 UTC, polybassa commented
@gpotter2 This PR is ready for review.

2022-05-22 06:26 UTC, polybassa commented
closed reopen to trigger tests again

2022-06-09 13:58 UTC, polydroi commented
@gpotter2  this pr is ready for merge

2022-06-18 22:36 UTC, gpotter2 commented
Could you rebase against master all your current PRs? Sorry about that, they were caught up in a workflow update :/

2022-06-19 20:04 UTC, gpotter2 requested changes

2022-06-19 20:04 UTC, gpotter2 commented on test/contrib/automotive/gm/scanner.uts
> +        while True:
This looks crappy. Was this to fail, it would hang

2022-06-19 20:04 UTC, gpotter2 commented on test/contrib/automotive/scanner/uds_scanner.uts
> +        while True:
same, we really don't want `while True: retry` loops

2022-06-20 05:58 UTC, polybassa commented
@gpotter2 Thanks for your feedback. Applied it.

2022-06-21 20:39 UTC, merged