[Hinty] Core typing: windows
secdev/scapy pull request #3684
Opened 2022-07-11 22:58 UTC by gpotter2

It's been a long time since I've done one of those.

- Core typing of Windows
- Change the mypy CI to test Linux AND Windows independently
- bunch of fixes everywhere, especially inconsistencies with the use of `NetworkInterface` or `str` in routes, that were sometimes messed up (but it worked because `NetworkInterface` can act as a string for backward compatibility)

2022-07-12 06:40 UTC, gpotter2 commented on .config/mypy/mypy.ini
> +implicit_reexport = True
This is required because we have star imports in `scapy.arch` we can hardly get rid of (used for polyfill)

2022-07-23 12:57 UTC, gpotter2 commented
@guedou @p-l- This is ready for review. This is pretty interesting IMHO because it uses mypy's ability to specify the platform.

2022-08-29 10:16 UTC, p-l- requested changes
Apart from a tiny change, LGTM. Thanks!

2022-08-29 10:16 UTC, p-l- commented on .config/mypy/mypy_check.py
> +            ]
```suggestion
            x not in {
                # Disabled on Windows
                "scapy/arch/linux.py",
                "scapy/arch/solaris.py",
                "scapy/contrib/cansocket_native.py",
                "scapy/contrib/isotp/isotp_native_socket.py",
            }
```

2022-08-30 08:41 UTC, p-l- approved these changes

2022-08-30 08:41 UTC, merged