Improve parsing for scapy.contrib.postgres
secdev/scapy pull request #3715
Opened 2022-08-15 18:02 UTC by jrolli

This fixes two major usability issues with the existing code:
1) Parsing of Bind messages
2) Proper reassembly of multi-packet message groups

Additionally, it makes minor changes to some of the existing code
that was causing bad parsing on real server traffic mostly focused
on length/count calculations.

Known bugs:

- This may error out on asynchronous server-generated messages
    (e.g. NoticeResponse & NotificationResponse) because of the
    simplified logic in `tcp_reassemble`.  I did not have any examples
    of this happening in real traces, so did not address at this time.

- Does not handle FunctionCall messages.  This was not implemented
    in the original code (commented out as a "TODO") but now it is
    replaced with a "_Todo" packet that allows parsing to continue for
    other messages in the stream (message packets follow a consistent
    TLV format).

2022-08-21 14:20 UTC, p-l- requested changes
Some tiny changes are needed.

Also, could you some tests to cover your changes?

Thanks!

2022-08-29 14:05 UTC, jrolli commented
@p-l-, thanks for the feedback!  I made the two code changes and added a test that checks the class I added (Bind) as well as the one I fixed (Parse).  Let me know if there are any other changes you would like to see.

2022-08-29 16:26 UTC, p-l- requested changes
Sorry to be so picky, just another (very) tiny change please!

2022-08-29 16:26 UTC, p-l- commented on test/contrib/postgres.uts
> +assert sync_msg.len == 4
Would you mind adding a newline at the end of this file?

2022-08-29 19:16 UTC, p-l- approved these changes

2022-08-29 19:26 UTC, merged