Improve reduce function for Automotive Scanner Enumerators
secdev/scapy pull request #3740
Opened 2022-09-19 06:06 UTC by polybassa

2022-09-20 20:48 UTC, p-l- requested changes
Apart for those tiny changes, LGTM

2022-09-20 20:48 UTC, p-l- commented on scapy/contrib/automotive/scanner/enumerator.py
> +            for k, v in d["_request_iterators"].items():
```suggestion
            for k, v in six.iteritems(d["_request_iterators"]):
```

2022-09-20 20:48 UTC, p-l- commented on scapy/contrib/automotive/scanner/enumerator.py
> +            for k in d["_retry_pkt"].keys():
```suggestion
            for k in d["_retry_pkt"]:
```

2022-09-20 20:48 UTC, p-l- commented on test/contrib/automotive/scanner/uds_scanner.uts
> +assert e._retry_pkt[s] == []
For consistency
```suggestion
assert not e._retry_pkt[s]
```

2022-09-20 20:48 UTC, p-l- commented on test/contrib/automotive/scanner/uds_scanner.uts
> +assert e._retry_pkt[s] == []
```suggestion
assert not e._retry_pkt[s]
```

2022-09-20 20:48 UTC, p-l- commented on test/contrib/automotive/scanner/uds_scanner.uts
> +assert e._retry_pkt[s] == []
```suggestion
assert not e._retry_pkt[s]
```

2022-09-20 20:48 UTC, p-l- commented on test/contrib/automotive/scanner/uds_scanner.uts
> +assert e._retry_pkt[s] == []
```suggestion
assert not e._retry_pkt[s]
```

2022-09-20 20:48 UTC, p-l- commented on test/contrib/automotive/scanner/uds_scanner.uts
> +assert e._retry_pkt[s] == []
```suggestion
assert not e._retry_pkt[s]
```

2022-09-20 20:48 UTC, p-l- commented on test/contrib/automotive/scanner/uds_scanner.uts
> +assert e._retry_pkt[s] == []
```suggestion
assert not e._retry_pkt[s]
```

2022-09-21 06:12 UTC, polybassa commented
Thanks a lot for your review!

2022-09-21 06:28 UTC, p-l- commented
Tests failures seem unrelated, re-running the failed tests

2022-09-21 06:45 UTC, p-l- approved these changes

2022-09-21 06:58 UTC, merged