CDP: add CDPMsgPowerRequest and CDPMsgPowerAavaiable
secdev/scapy pull request #3805
Opened 2022-11-30 15:13 UTC by cq674350529

refine CDPMsgPowerRequest and CDPMsgPowerAvailable based on the output from Whireshark

For your convenience, a sample of pcap is attached

[cdp_power.zip](https://github.com/secdev/scapy/files/10124456/cdp_power.zip)

2022-12-01 12:41 UTC, mspncp commented
fly-by-comment: there is a typo in the subject line of your commit (and the PR title):   CDPMsgPowerAavaiable ->  CDPMsgPowerAavailable

2022-12-01 14:05 UTC, cq674350529 commented
@mspncp Thanks, fixed the typos :)

2023-01-31 21:24 UTC, gpotter2 requested changes
Hi ! really sorry for the delay. Could you add a unit test to https://github.com/secdev/scapy/blob/master/test/contrib/cdp.uts ? Thanks !

2023-01-31 21:24 UTC, gpotter2 commented on scapy/contrib/cdp.py
> +                                  count_from=lambda pkt: (pkt.len - 8) / 4)]
```suggestion
                                  count_from=lambda pkt: (pkt.len - 8) // 4)]
```

2023-01-31 21:24 UTC, gpotter2 commented on scapy/contrib/cdp.py
> +                                  count_from=lambda pkt: (pkt.len - 8) / 4)]
```suggestion
                                  count_from=lambda pkt: (pkt.len - 8) // 4)]
```

2023-02-01 05:26 UTC, cq674350529 commented
Thanks for the suggestions, I updated them and added an unit test for it.

2024-02-05 22:25 UTC, gpotter2 approved these changes

2024-02-05 22:26 UTC, merged

2024-02-05 22:26 UTC, gpotter2 commented
Very sorry for the delay !