when aead is not used, esn is added to the end of packet
secdev/scapy pull request #3908
Opened 2023-02-20 10:55 UTC by phuhavan

**Checklist:**

-   [ ] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [ ] I squashed commits belonging together
-   [ ] I added unit tests or explained why they are not relevant
-   [ ] I executed the regression tests (using `cd test && ./run_tests` or `tox`)
-   [ ] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

Based on rfc4303 / 2.2.1. Extended (64-bit) Sequence Number
 If a separate integrity algorithm is employed, the high
 order bits are included in the implicit ESP trailer, but are not
 transmitted, analogous to integrity algorithm padding bits. 

So, for ESP mode when aead is not used, we need to add ESN to the end of packet to be authenticated (if authentication operation is required)

2023-02-20 14:45 UTC, guedou commented
Thanks for your interest in Scapy. Could you share an example that triggers the issue?

2023-02-20 21:11 UTC, phuhavan commented
For example: 

`data = 'hello world'
pkt_in = IP()/TCP()/data

enc_key = b'\x85\xee\x35\x4b\x46\x75\xa9\xc5\xd1\x6e\x3d\x6f\x41\x18\x04\x3b'
auth_key = b'\x6f\x79\xbf\x94\xda\x7d\xde\x3c\x86\x00\x99\x34\xd9\x25\x8f\x1b\x3f\xc2\xf5\x38\x2a\xca\x9c\x9c\xb8\xe2\x16\xee\xd2\x35\xf3\x4c'

sa = SecurityAssociation(ESP, spi=0xcf54ccdf, crypt_algo='AES-CBC', crypt_key=enc_key, 
                         auth_algo='SHA2-256-128', auth_key=auth_key,
                         esn_en=True, esn=68)
pkt_processed = sa.encrypt(pkt=pkt_in, iv=b'\x11\x22\x33\x44\x11\x22\x33\x44\x11\x22\x33\x44\x11\x22\x33\x44')`

When print `raw(pkt_processed )`, we should obtain:
`\x45\x00\x00\x6c\x00\x01\x00\x00\x40\x32\x39\x8a\xc0\xa8\x01\x2c\x7f\x00\x00\x01\xcf\x54\xcc\xdf\x00\x00\x00\x01\x11\x22\x33\x44\x11\x22\x33\x44\x11\x22\x33\x44\x11\x22\x33\x44\x56\x00\x34\xf4\x2c\x6e\xa9\xae\x47\x5b\x8d\x3d\x80\xda\x14\xd8\x30\xf7\x4e\xdc\x89\x42\x1d\x9d\x63\x6c\xa5\xbc\x76\x2b\x4d\xeb\xa8\x99\x40\x8b\xfd\xa5\x46\x5d\xc2\x82\xd2\x5b\xdd\x20\x9a\x20\x07\xb2\xe6\x44\xb6\xe4\xaa\x84\x2f\xe8\xab\xa8\xd6\xf3\x59\x0e
`

2023-02-28 13:28 UTC, phuhavan commented
Hello, could you take a look on this problem?

2023-02-28 15:35 UTC, guedou commented
Would you mind adding your example as a unit test here https://github.com/secdev/scapy/blob/master/test/scapy/layers/ipsec.uts#L4107

You can add a title for the test using `=`, then add Python code and eventually an assert to check for the correct value,

2023-02-28 20:02 UTC, guedou submitted a review, later dismissed

2023-02-28 21:22 UTC, phuhavan commented
I modified the test a bit to avoid the long code line

2023-03-05 13:50 UTC, gpotter2 commented
The test is failing :/

2023-03-20 10:50 UTC, phuhavan commented
Hello, 

Could you explain why the test is failed?
I just saw this error message but not sure why it happens:

>>> assert raw(pkt_processed) == bytes(bytearray.fromhex(
...     "4500006c000100004032398ac0a8012c7f000001cf54ccdf000000011122"
...     "3344112233441122334411223344560034f42c6ea9ae475b8d3d80da14d8"
...     "30f74edc89421d9d636ca5bc762b4deba899408bfda5465dc282d25bdd20"
...     "9a2007b2e644b6e4aa842fe8aba8d6f3590e"))
Traceback (most recent call last):
  File "<input>", line 3, in <module>
AssertionError

2023-03-20 11:57 UTC, p-l- requested changes

2023-03-20 11:57 UTC, p-l- commented on test/scapy/layers/ipsec.uts
> +    "9a2007b2e644b6e4aa842fe8aba8d6f3590e"))
`.uts` files are not "real" Python files.

This should work

```suggestion
assert raw(pkt_processed) == bytes(bytearray.fromhex("4500006c000100004032398ac0a8012c7f000001cf54ccdf0000000111223344112233441122334411223344560034f42c6ea9ae475b8d3d80da14d830f74edc89421d9d636ca5bc762b4deba899408bfda5465dc282d25bdd209a2007b2e644b6e4aa842fe8aba8d6f3590e"))
```

2023-03-21 06:29 UTC, evverx commented
> Could you explain why the test is failed?

Looks like the last assertion failed because `raw(pkt_processed)` is different from `bytes.fromhex(...)`:
```sh
>>> raw(pkt_processed)
b'E\x00\x00l\x00\x01\x00\x00@2|]\x7f\x00\x00\x01\x7f\x00\x00\x01\xcfT\xcc\xdf\x00\x00\x00\x01\x11"3D\x11"3D\x11"3D\x11"3DV\x004\xf4,n\xa9\xaeG[\x8d=\x80\xda\x14\xd8y\xb0\x05\xdc\xc3\xcf\xac\x1a\xfc\xb2U\x9d-\xde\xbc\xf2\x0c\x8eq\x1bQ\xbb\xbb\xb8\xb33\x8ePB\xbf"\xf5\t\xd0\xf4\x80\xebK\xbd\x0eMv\x07\t\xed%\xfa\x1e'

>>> bytes(bytearray.fromhex("4500006c000100004032398ac0a8012c7f000001cf54ccdf0000000111223344112233441122334411223344560034f42c6ea9ae475b8d3d80da14d830f74edc89421d9d636ca5bc762b4deba899408bfda5465dc282d25bdd209a200
...: 7b2e644b6e4aa842fe8aba8d6f3590e"))
b'E\x00\x00l\x00\x01\x00\x00@29\x8a\xc0\xa8\x01,\x7f\x00\x00\x01\xcfT\xcc\xdf\x00\x00\x00\x01\x11"3D\x11"3D\x11"3D\x11"3DV\x004\xf4,n\xa9\xaeG[\x8d=\x80\xda\x14\xd80\xf7N\xdc\x89B\x1d\x9dcl\xa5\xbcv+M\xeb\xa8\x99@\x8b\xfd\xa5F]\xc2\x82\xd2[\xdd \x9a \x07\xb2\xe6D\xb6\xe4\xaa\x84/\xe8\xab\xa8\xd6\xf3Y\x0e'
```
It can be reproduced by launching `scapy` with `./run_scapy` and copy-pasting the test case.

2023-03-22 06:44 UTC, mspncp commented on scapy/layers/ipsec.py
FWIW:  the changes in ipsec.py look ok to me, at least they are consistent with the analogous change 8b45cbf8545ae1a8948860e234c7d97124f6d1ac for the AH protocol.

_(I tried to double-check with Wireshark, but it seems that Wireshark does not handle ESNs. Or at least I wasn't able to find out how to configure the ESP SA accordingly.)_

2024-02-05 21:57 UTC, gpotter2 approved these changes

2024-02-05 22:05 UTC, merged