Add more HCI command and event packets
secdev/scapy pull request #4003
Opened 2023-05-03 07:41 UTC by gsingh93

**Checklist:**

-   [X] If you are new to Scapy: I have checked [CONTRIBUTING.md](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md) (esp. section submitting-pull-requests)
-   [X] I squashed commits belonging together
-   [ ] I added unit tests or explained why they are not relevant
-   [ ] I executed the regression tests (using `cd test && ./run_tests` or `tox`)
-   [X] If the PR is still not finished, please create a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/)

This PR adds some additional HCI command and event types. With these additional commands and events, it is possible to create a full Bluetooth Classic connection with an endpoint. For reference, these are section numbers in Volume 4, Part E of the Bluetooth 5.3 specification where these types are defined: 7.1.5, 7.1.10, 7.1.15, 7.1.16, 7.1.19

This is currently a draft PR as I haven't had time to investigate how to add and run tests.

2023-05-19 04:18 UTC, gsingh93 commented
This is ready for review, can someone kick off the required workflows?

I'm not sure why test coverage decreased 2.6%, my added code should have 100% coverage: https://app.codecov.io/gh/secdev/scapy/pull/4003

2023-05-26 22:03 UTC, gsingh93 commented
Ping @guedou or @p-l-, can I get a review for this?

2023-05-27 01:20 UTC, p-l- approved these changes

2023-06-11 15:14 UTC, gpotter2 requested changes

2023-06-11 15:14 UTC, gpotter2 commented on test/scapy/layers/bluetooth.uts
> -pkt = HCI_ACL_Hdr()/HCI_Cmd_Complete_Read_BD_Addr()/HCI_Cmd_Connect_Accept_Timeout()/HCI_Cmd_Disconnect()/HCI_Cmd_LE_Connection_Update()/HCI_Cmd_LE_Create_Connection()/HCI_Cmd_LE_Create_Connection_Ca
Sorry for the delay. Could you add a proper test? (build/dissect some packets). This one is absurd and should eventually be deleted.
Thanks !

2023-06-15 23:00 UTC, gsingh93 commented
@gpotter2 I added some more tests, can you take another look?

2023-06-21 11:06 UTC, p-l- commented
Hey @gsingh93 can you rebase against current master? That should fix the failing test.

2023-06-21 16:01 UTC, gsingh93 commented
@p-l- done

2023-06-21 18:40 UTC, p-l- commented
@gsingh93 perfect. Now @gpotter2 is it OK on your side (since you had requested changes)?

2023-06-21 18:44 UTC, gpotter2 approved these changes
Thanks for addressing this !

2023-06-21 20:24 UTC, merged

2023-06-21 20:24 UTC, p-l- commented
Thank you @gsingh93!