Scapy terminal improvements
secdev/scapy pull request #4073
Opened 2023-07-18 21:28 UTC by gpotter2

This commit changes the following:
- `.scapy_startup.py` and `.scapy_prestart.py` are moved to `.config/scapy/startup.py` and `.config/scapy/prestart.py`. This is what apparently most big libraries/softwares are moving towards (matplotlib, wireshark, etc.). Question: do we want to move the history there? (for now it's the only file remaining in ~)
- automatically create `.config/scapy/prestart.py`. This is IMHO much easier for a novice user to understand what's going on, since it will show what it is supposed to look like.
- the Scapy terminal now supports **`ptpython`** and **`bpython`**, in addition to the existing **`IPython`**. `ptpython` comes with the **`ptipython`** variant that's a mix between `ptpython` and `IPython`.

bpython requires the https://github.com/bpython/bpython/pull/992 patch.

Honnestly I encourage you to try them all a bit, some are pretty fun, and you might find one that fits better :p

2023-07-21 10:40 UTC, guedou commented
@gpotter2 I am fine with moving everything into `.config/scapy` that makes more sense.

2023-07-21 10:45 UTC, guedou commented on scapy/main.py
> +@overload
Can you explain the rationale to overload `init_session()`?  I did not understand it on my own.

2023-07-21 10:51 UTC, guedou requested changes

2023-07-21 10:51 UTC, guedou commented on scapy/main.py
> +    # Check bpython import
Could factor the Python shell checks? The following lines looks redundant.

2023-07-21 10:51 UTC, guedou commented on scapy/main.py
> +        log_loading.warning("ptpython support is currently partially broken")
Can you add a comment explaining why?

2023-07-22 15:28 UTC, gpotter2 commented on scapy/main.py
> +        log_loading.warning("ptpython support is currently partially broken")
Done !

2023-07-24 19:04 UTC, guedou commented on scapy/main.py
> +@overload
Thanks!

2023-07-28 06:48 UTC, gpotter2 commented
@guedou @polybassa @p-l- Ready for review & merge !

2023-07-30 16:27 UTC, guedou commented
LGTM.Thanks for the changes. I don't why but I cannot approve the PR.

2023-07-31 06:10 UTC, polybassa approved these changes

2023-07-31 16:36 UTC, p-l- approved these changes

2023-07-31 18:02 UTC, merged